In [35]:
import pandas as pd

b) Remove the units from some of the attributes and only keep the numerical values (for example remove kmpl from “Mileage”, CC from “Engine”, bhp from “Power”, and lakh from “New_price”).

In [36]:
car_data=pd.read_csv('cleaned_data.csv')
car_data

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,4.78 Lakh,12.50
1,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,4.78 Lakh,6.00
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,4.78 Lakh,17.74
4,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,4.78 Lakh,3.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5842,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75
5843,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,4.78 Lakh,4.00
5844,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,4.78 Lakh,2.90
5845,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,4.78 Lakh,2.65
5846,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,4.78 Lakh,2.50

In [13]:
car_data['Mileage'] = car_data['Mileage'].str.replace('kmpl', '').str.replace('km/kg', '').astype(float)
car_data['Engine'] = car_data['Engine'].str.replace('CC', '').astype(float)
car_data['Power'] = car_data['Power'].str.replace('bhp', '').astype(float)
car_data['New_Price'] = car_data['New_Price'].str.replace('Lakh', '').str.replace('Cr', '').astype(float)

In [14]:
car_data

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,4.78,12.50
1,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13.00,1199.0,88.70,5.0,8.61,4.50
2,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,4.78,6.00
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,4.78,17.74
4,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461.0,63.10,5.0,4.78,3.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5842,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.40,1248.0,74.00,5.0,7.88,4.75
5843,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.40,1120.0,71.00,5.0,4.78,4.00
5844,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.00,2498.0,112.00,8.0,4.78,2.90
5845,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.90,998.0,67.10,5.0,4.78,2.65
5846,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936.0,57.60,5.0,4.78,2.50

C) Change the categorical variables (“Fuel_Type” and “Transmission”) into numerical one hot encoded value.

In [15]:
car_cat_data = pd.get_dummies(car_data, columns=['Fuel_Type', 'Transmission'])

In [17]:
car_cat_data

,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.20,5.0,4.78,12.50,True,False,False,False,True
1,Honda Jazz V,Chennai,2011,46000,First,13.00,1199.0,88.70,5.0,8.61,4.50,False,False,True,False,True
2,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248.0,88.76,7.0,4.78,6.00,True,False,False,False,True
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968.0,140.80,5.0,4.78,17.74,True,False,False,True,False
4,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461.0,63.10,5.0,4.78,3.50,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5842,Maruti Swift VDI,Delhi,2014,27365,First,28.40,1248.0,74.00,5.0,7.88,4.75,True,False,False,False,True
5843,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,First,24.40,1120.0,71.00,5.0,4.78,4.00,True,False,False,False,True
5844,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Second,14.00,2498.0,112.00,8.0,4.78,2.90,True,False,False,False,True
5845,Maruti Wagon R VXI,Kolkata,2013,46000,First,18.90,998.0,67.10,5.0,4.78,2.65,False,False,True,False,True
5846,Chevrolet Beat Diesel,Hyderabad,2011,47000,First,25.44,936.0,57.60,5.0,4.78,2.50,True,False,False,False,True

In [16]:
car_cat_data.to_csv('car_data_encoded.csv', index=False)

d) Create one more feature and add this column to the dataset (you can use mutate function in R for this). For example, you can calculate the current age of the car by subtracting “Year” value from the current year

In [18]:
import datetime

In [19]:
car_data_lat=pd.read_csv('car_data_encoded.csv')

In [20]:

current_year = datetime.datetime.now().year

In [21]:
car_data_lat['Current_Age'] = current_year - car_data_lat['Year']

In [22]:
car_data_lat

,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Current_Age
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.20,5.0,4.78,12.50,True,False,False,False,True,9
1,Honda Jazz V,Chennai,2011,46000,First,13.00,1199.0,88.70,5.0,8.61,4.50,False,False,True,False,True,13
2,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248.0,88.76,7.0,4.78,6.00,True,False,False,False,True,12
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968.0,140.80,5.0,4.78,17.74,True,False,False,True,False,11
4,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461.0,63.10,5.0,4.78,3.50,True,False,False,False,True,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5842,Maruti Swift VDI,Delhi,2014,27365,First,28.40,1248.0,74.00,5.0,7.88,4.75,True,False,False,False,True,10
5843,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,First,24.40,1120.0,71.00,5.0,4.78,4.00,True,False,False,False,True,9
5844,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Second,14.00,2498.0,112.00,8.0,4.78,2.90,True,False,False,False,True,12
5845,Maruti Wagon R VXI,Kolkata,2013,46000,First,18.90,998.0,67.10,5.0,4.78,2.65,False,False,True,False,True,11
5846,Chevrolet Beat Diesel,Hyderabad,2011,47000,First,25.44,936.0,57.60,5.0,4.78,2.50,True,False,False,False,True,13

e) Perform select, filter, rename, mutate, arrange and summarize with group by operations (or their equivalent operations in python) on this dataset.

select

In [26]:

select_car_data_lat = car_data_lat[['Name', 'Location', 'Year', 'Price']]
select_car_data_lat.head()

                               Name    Location  Year  Price
0  Hyundai Creta 1.6 CRDi SX Option        Pune  2015  12.50
1                      Honda Jazz V     Chennai  2011   4.50
2                 Maruti Ertiga VDI     Chennai  2012   6.00
3   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013  17.74
4            Nissan Micra Diesel XV      Jaipur  2013   3.50

filter

In [25]:

filter_car_data_lat = car_data_lat[(car_data_lat['Year'] == 2015) & (car_data_lat['Owner_Type'] == 'First')]

filter_car_data_lat

,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Current_Age
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.20,5.0,4.78,12.50,True,False,False,False,True,9
10,Maruti Swift VDI BSIV,Jaipur,2015,64424,First,25.20,1248.0,74.00,5.0,4.78,5.60,True,False,False,False,True,9
20,Audi A6 2011-2015 35 TFSI Technology,Mumbai,2015,55985,First,13.53,1984.0,177.01,5.0,4.78,23.50,False,False,True,True,False,9
48,Audi A4 2.0 TDI 177 Bhp Premium Plus,Kochi,2015,13648,First,17.11,1968.0,174.33,5.0,4.78,21.43,True,False,False,True,False,9
53,Volkswagen Vento 2013-2015 1.6 Comfortline,Kolkata,2015,39000,First,15.04,1598.0,103.20,5.0,4.78,3.99,False,False,True,False,True,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5824,Renault Duster 85PS Diesel RxL Explore,Pune,2015,30000,First,19.87,1461.0,83.80,5.0,4.78,7.75,True,False,False,False,True,9
5831,Maruti Celerio VXI,Bangalore,2015,67600,First,23.10,998.0,67.04,5.0,4.78,4.00,False,False,True,False,True,9
5837,Toyota Camry Hybrid,Mumbai,2015,33500,First,19.16,2494.0,158.20,5.0,4.78,19.75,False,False,True,True,False,9
5841,Honda Amaze VX i-DTEC,Coimbatore,2015,70602,First,25.80,1498.0,98.60,5.0,4.78,4.83,True,False,False,False,True,9
5843,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,First,24.40,1120.0,71.00,5.0,4.78,4.00,True,False,False,False,True,9

Rename

In [27]:

rename_car_data_lat = car_data_lat.rename(columns={'Kilometers_Driven': 'KM_Driven'})
rename_car_data_lat.head()

,Name,Location,Year,KM_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Current_Age
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.20,5.0,4.78,12.50,True,False,False,False,True,9
1,Honda Jazz V,Chennai,2011,46000,First,13.00,1199.0,88.70,5.0,8.61,4.50,False,False,True,False,True,13
2,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248.0,88.76,7.0,4.78,6.00,True,False,False,False,True,12
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968.0,140.80,5.0,4.78,17.74,True,False,False,True,False,11
4,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461.0,63.10,5.0,4.78,3.50,True,False,False,False,True,11

 mutate

In [29]:

rename_car_data_lat['Price_per_KM'] = rename_car_data_lat['Price'] / rename_car_data_lat['KM_Driven']
rename_car_data_lat[['Name', 'KM_Driven', 'Price', 'Price_per_KM']].head()

                               Name  KM_Driven  Price  Price_per_KM
0  Hyundai Creta 1.6 CRDi SX Option      41000  12.50      0.000305
1                      Honda Jazz V      46000   4.50      0.000098
2                 Maruti Ertiga VDI      87000   6.00      0.000069
3   Audi A4 New 2.0 TDI Multitronic      40670  17.74      0.000436
4            Nissan Micra Diesel XV      86999   3.50      0.000040

In [33]:
rename_car_data_lat

,Name,Location,Year,KM_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Current_Age,Price_per_KM
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.20,5.0,4.78,12.50,True,False,False,False,True,9,0.000305
1,Honda Jazz V,Chennai,2011,46000,First,13.00,1199.0,88.70,5.0,8.61,4.50,False,False,True,False,True,13,0.000098
2,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248.0,88.76,7.0,4.78,6.00,True,False,False,False,True,12,0.000069
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968.0,140.80,5.0,4.78,17.74,True,False,False,True,False,11,0.000436
4,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461.0,63.10,5.0,4.78,3.50,True,False,False,False,True,11,0.000040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5842,Maruti Swift VDI,Delhi,2014,27365,First,28.40,1248.0,74.00,5.0,7.88,4.75,True,False,False,False,True,10,0.000174
5843,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,First,24.40,1120.0,71.00,5.0,4.78,4.00,True,False,False,False,True,9,0.000040
5844,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Second,14.00,2498.0,112.00,8.0,4.78,2.90,True,False,False,False,True,12,0.000053
5845,Maruti Wagon R VXI,Kolkata,2013,46000,First,18.90,998.0,67.10,5.0,4.78,2.65,False,False,True,False,True,11,0.000058
5846,Chevrolet Beat Diesel,Hyderabad,2011,47000,First,25.44,936.0,57.60,5.0,4.78,2.50,True,False,False,False,True,13,0.000053

In [34]:
rename_car_data_lat.to_csv('final_car_data.csv', index=False)

Arrange

In [30]:

sorted_car_data_lat = rename_car_data_lat.sort_values(by='Price', ascending=False)
sorted_car_data_lat[['Name', 'Price']].head()

                                             Name   Price
3952  Land Rover Range Rover 3.0 Diesel LWB Vogue  160.00
5620                   Lamborghini Gallardo Coupe  120.00
5752                       Jaguar F Type 5.0 V8 S  100.00
1457              Land Rover Range Rover Sport SE   97.07
1917                           BMW 7 Series 740Li   93.67

Summarize

In [32]:
summary_car_data_lat = rename_car_data_lat.groupby('Location').agg(average_price=('Price', 'mean'))
summary_car_data_lat

            average_price
Location
Ahmedabad        8.567248
Bangalore       13.482670
Chennai          7.958340
Coimbatore      15.160206
Delhi            9.881944
Hyderabad        9.997423
Jaipur           5.916725
Kochi           11.309109
Kolkata          5.733924
Mumbai           9.592546
Pune             6.951000